### PR TITLE
Update readme to show commit codes by default

### PR DESCRIPTION
**Pull request by thclark**
### Documentation
- [x] Update readme to show commit codes by default

### CODE REVIEW

**Review by cortadocodes — APPROVED** [review]
Looks good to me. Should I be using `-` instead of `*` for bullet points in markdown or is that just choice if they both render to the same thing?

**Comment by thclark** [comment]
> Looks good to me. Should I be using `-` instead of `*` for bullet points in markdown or is that just choice if they both render to the same thing?

I usually use `-` because it disambiguates problems where you're trying to make something `*italic*` but you put an extra space in like `* italic`.

**Comment by cortadocodes** [comment]
> > Looks good to me. Should I be using `-` instead of `*` for bullet points in markdown or is that just choice if they both render to the same thing?
> 
> I usually use `-` because it disambiguates problems where you're trying to make something `*italic*` but you put an extra space in like `* italic`. But it's personal preference, don't think it's significant enough to make a style guide entry over

Ah I see, that's a good point

**Comment by cortadocodes** [comment]
@thclark do you think readme-only changes warrant a patch version increase? Nothing would change for anybody using this package

**Comment by thclark** [comment]
> @thclark do you think readme-only changes warrant a patch version increase? Nothing would change for anybody using this package. We could keep the version the same and skip the release adding `skip_ci_release` to the final PR commit

Yes, they do. A release should always correspond with a unique SHA, and under our gitops pattern, main should always be a release.

Normally I’d have left this for pulling into a bigger piece of work, just needed it to link to for the website guy.

**Pull request merged**
